import { createFileRoute } from "@tanstack/react-router";
import { Check, Clock3, LockKeyhole } from "lucide-react";
import { useState } from "react";
import { AppShell } from "../components/space-colony/AppShell";
import { PageHeading, ProgressBar, StatusBadge } from "../components/space-colony/Common";
import { researchBranches } from "../components/space-colony/data";
import { Button } from "../components/ui/Button";
export const Route=createFileRoute("/research")({head:()=>({meta:[{title:"Research | Space Colony"},{name:"description",content:"Advance agriculture, engineering, and life support technologies for New Horizon."},{property:"og:title",content:"Research | Space Colony"},{property:"og:description",content:"Explore the Space Colony technology tree."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:ResearchPage});
function ResearchPage(){const [active,setActive]=useState("Improved Agriculture");return <AppShell><PageHeading eyebrow="Science division" title="Research" description="Direct limited research capacity toward technologies that improve survival and expansion." action={<div className="text-right"><p className="text-xs text-muted-foreground">Available iron</p><p className="font-bold">50</p></div>}/><section className="mb-6 rounded-md border border-primary/30 bg-primary/7 p-5"><div className="mb-3 grid grid-cols-[minmax(0,1fr)_auto] gap-3"><div><p className="text-xs font-bold uppercase text-primary">Active research</p><h2 className="mt-1 font-semibold">{active}</h2></div><StatusBadge tone="info">65%</StatusBadge></div><ProgressBar value={65}/><div className="mt-3 flex justify-between text-xs text-muted-foreground"><span>Only one project can run at a time</span><span>12 minutes remaining</span></div></section><div className="grid gap-5 xl:grid-cols-3">{researchBranches.map(branch=>{const Icon=branch.icon;return <section key={branch.name}><div className="mb-4 flex items-center gap-3 border-b border-border pb-3"><span className="grid size-9 place-items-center rounded-md bg-secondary text-primary"><Icon size={18}/></span><h2 className="font-semibold">{branch.name}</h2></div><div className="space-y-0">{branch.nodes.map((node,index)=>{const state=node.name===active?"Researching":node.state;return <div key={node.name} className="relative pb-8 last:pb-0">{index<branch.nodes.length-1&&<span className="absolute left-5 top-12 h-[calc(100%-2rem)] w-px bg-border"/>}<article className={`relative rounded-md border p-5 ${state==="Researching"?"border-primary bg-primary/7":"border-border bg-card"}`}><div className="mb-4 flex items-start justify-between gap-3"><div><h3 className="font-semibold">{node.name}</h3><p className="mt-1 text-xs text-positive">{node.effect}</p></div>{state==="Locked"?<LockKeyhole size={16} className="text-muted-foreground"/>:state==="Completed"?<Check size={16} className="text-positive"/>:<StatusBadge tone={state==="Researching"?"info":"neutral"}>{state}</StatusBadge>}</div><div className="mb-5 grid grid-cols-2 text-xs"><div><p className="text-muted-foreground">Cost</p><p className="mt-1 font-semibold">{node.cost} Iron</p></div><div><p className="text-muted-foreground">Duration</p><p className="mt-1 flex items-center gap-1 font-semibold"><Clock3 size={12}/>{node.duration}</p></div></div>{state==="Researching"?<><ProgressBar value={65}/><p className="mt-2 text-right text-xs text-muted-foreground">12 min remaining</p></>:state==="Completed"?<p className="text-xs font-semibold text-positive">Research completed</p>:<Button size="sm" variant="secondary" disabled={state==="Locked"||Boolean(active)} onClick={()=>setActive(node.name)}>{state==="Locked"?"Prerequisite required":"Start research"}</Button>}</article></div>})}</div></section>})}</div></AppShell>}
