/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildingsRouteImport } from './routes/buildings'
import { Route as ColonistsRouteImport } from './routes/colonists'
import { Route as ColonyRouteImport } from './routes/colony'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ExplorationRouteImport } from './routes/exploration'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingsRoute = BuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => rootRouteImport,
} as any)
const ColonistsRoute = ColonistsRouteImport.update({
  id: '/colonists',
  path: '/colonists',
  getParentRoute: () => rootRouteImport,
} as any)
const ColonyRoute = ColonyRouteImport.update({
  id: '/colony',
  path: '/colony',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorationRoute = ExplorationRouteImport.update({
  id: '/exploration',
  path: '/exploration',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buildings': typeof BuildingsRoute
  '/colonists': typeof ColonistsRoute
  '/colony': typeof ColonyRoute
  '/events': typeof EventsRoute
  '/exploration': typeof ExplorationRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buildings': typeof BuildingsRoute
  '/colonists': typeof ColonistsRoute
  '/colony': typeof ColonyRoute
  '/events': typeof EventsRoute
  '/exploration': typeof ExplorationRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buildings': typeof BuildingsRoute
  '/colonists': typeof ColonistsRoute
  '/colony': typeof ColonyRoute
  '/events': typeof EventsRoute
  '/exploration': typeof ExplorationRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buildings'
    | '/colonists'
    | '/colony'
    | '/events'
    | '/exploration'
    | '/login'
    | '/register'
    | '/research'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buildings'
    | '/colonists'
    | '/colony'
    | '/events'
    | '/exploration'
    | '/login'
    | '/register'
    | '/research'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/buildings'
    | '/colonists'
    | '/colony'
    | '/events'
    | '/exploration'
    | '/login'
    | '/register'
    | '/research'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildingsRoute: typeof BuildingsRoute
  ColonistsRoute: typeof ColonistsRoute
  ColonyRoute: typeof ColonyRoute
  EventsRoute: typeof EventsRoute
  ExplorationRoute: typeof ExplorationRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResearchRoute: typeof ResearchRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildings': {
      id: '/buildings'
      path: '/buildings'
      fullPath: '/buildings'
      preLoaderRoute: typeof BuildingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colonists': {
      id: '/colonists'
      path: '/colonists'
      fullPath: '/colonists'
      preLoaderRoute: typeof ColonistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colony': {
      id: '/colony'
      path: '/colony'
      fullPath: '/colony'
      preLoaderRoute: typeof ColonyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exploration': {
      id: '/exploration'
      path: '/exploration'
      fullPath: '/exploration'
      preLoaderRoute: typeof ExplorationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildingsRoute: BuildingsRoute,
  ColonistsRoute: ColonistsRoute,
  ColonyRoute: ColonyRoute,
  EventsRoute: EventsRoute,
  ExplorationRoute: ExplorationRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResearchRoute: ResearchRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
